### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by klipspringr** [mjmsmith/infodumpster#4]
Something weird is happening on https://infodumpster.org.

I'm seeing a mix of `421 Site infodumpster.org is not served on this interface`, `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` and `ERR_CERT_COMMON_NAME_INVALID` (the server responds with certificates for various other domains e.g. `www.breezyshores.com`, `www.starredsearch.com`, `camazotz.com`).

The HTTP site seems fine.

**Comment by mjmsmith** [comment]
Thanks for the report. Those other domains are hosted on the same server. I restarted the extremely long-running vintage  web server and it seems to have regenerated certs ok.
